routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Front\UserController;
use Illuminate\Foundation\Application;

use Inertia\Inertia;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
#Route::get('admin/panel','App\Http\Controllers\Back\Dashboard@index')->name('admin.dashboard');

Route::get('/', function () {
    return Inertia::render('Welcome', [
        'canLogin' => Route::has('login'),
        'canRegister' => Route::has('register'),
        'laravelVersion' => Application::VERSION,
        'phpVersion' => PHP_VERSION,
    ]);
});


// Admin

Route::get('admin/login', 'App\Http\Controllers\Admin\HomeController@login')->name('admin.auth.login');
Route::post('admin/login', 'App\Http\Controllers\Admin\HomeController@login_post')->name('admin.auth.login.post');


Route::prefix('admin')->name('admin.')->middleware('Admin')->group(function () {
    //user roles

    // posts
    Route::get('/', 'App\Http\Controllers\Admin\HomeController@index')->name('dashboard');
    Route::resource('posts', 'App\Http\Controllers\Admin\PostsController');
    Route::get('logout', 'App\Http\Controllers\Admin\HomeController@logout')->name('auth.logout');
    Route::get('register', 'App\Http\Controllers\Admin\HomeController@register')->name('auth.register');
    Route::get('forgetpassword', 'App\Http\Controllers\Admin\HomeController@forget')->name('auth.forget');
    Route::get('posts', 'App\Http\Controllers\Admin\PostsController@index')->name('posts.index');
    Route::get('switch', 'App\Http\Controllers\Admin\PostsController@switch')->name('switch');
    Route::put('hot_posts', 'App\Http\Controllers\Admin\PostsController@hot_posts')->name('hot_posts');
    Route::get('posts/create', 'App\Http\Controllers\Admin\PostsController@create')->name('posts.create');
    Route::get('create/{post_id}', 'App\Http\Controllers\Admin\ImageController@create')->name('admin_image_add');
    Route::post('store/{post_id}', 'App\Http\Controllers\Admin\ImageController@store')->name('admin_image_store');
    Route::get('delete/{id}/{post_id}', 'App\Http\Controllers\Admin\ImageController@destroy')->name('admin_image_delete');
    Route::get('show', 'App\Http\Controllers\Admin\ImageController@show')->name('admin_image_show');
    // Category
    Route::get('/categories', 'App\Http\Controllers\Admin\CategoryController@index')->name('category.index');
    Route::post('/categories/create', 'App\Http\Controllers\Admin\CategoryController@create')->name('category.create');
    Route::post('/categories/update', 'App\Http\Controllers\Admin\CategoryController@update')->name('category.update');
    Route::post('/categories/delete', 'App\Http\Controllers\Admin\CategoryController@delete')->name('category.delete');
    Route::post('/posts/delete/{id}', 'App\Http\Controllers\Admin\PostsController@delete')->name('posts.delete');
    Route::get('/categories/getData', 'App\Http\Controllers\Admin\CategoryController@getData')->name('category.getdata');
    // Page Route
    Route::get('/pages', 'App\Http\Controllers\Admin\PageController@index')->name('pages.index');
    Route::get('/pages/create', 'App\Http\Controllers\Admin\PageController@create')->name('pages.create');
    Route::post('/pages/create', 'App\Http\Controllers\Admin\PageController@createpost')->name('pages.create.post');
    Route::get('/pages/update/{id}', 'App\Http\Controllers\Admin\PageController@update')->name('pages.update');
    Route::post('/pages/update/{id}', 'App\Http\Controllers\Admin\PageController@updatepost')->name('pages.update.post');
    Route::get('/pages/switch', 'App\Http\Controllers\Admin\PageController@switch')->name('pages.switch');
    Route::post('/pages/delete/{id}', 'App\Http\Controllers\Admin\PageController@delete')->name('pages.delete');
    // Settings
    Route::get('/settings', 'App\Http\Controllers\Admin\SettingsController@index')->name('settings.index');
    Route::post('settings/update', 'App\Http\Controllers\Admin\SettingsController@update')->name('settings.update');

    // roles

    Route::get('/users', 'App\Http\Controllers\Admin\UserController@index')->name('users.index');
    Route::get('/users/create', 'App\Http\Controllers\Admin\UserController@create')->name('users.create');

    Route::post('/users/create', 'App\Http\Controllers\Admin\UserController@store')->name('users.store');
    Route::get('/users/{user}/edit', 'App\Http\Controllers\Admin\UserController@edit')->name('users.edit');
    Route::put('/users/{user}/update', 'App\Http\Controllers\Admin\UserController@update')->name('users.update');
    Route::delete('/users/{user}/delete', 'App\Http\Controllers\Admin\UserController@destroy')->name('users.destroy');

});


// User Login Route
Route::post('/user-login', [\App\Http\Controllers\Front\UserController::class, 'myprofile_post'])->name('user.login');
// User View
Route::middleware('auth')->prefix('myuser')->name('myuser.')->group(function () {
    Route::get('/myprofile', [\App\Http\Controllers\Front\UserController::class, 'index'])->name('myprofile');
    Route::post('/', [\App\Http\Controllers\Front\UserController::class, 'login_post'])->name('myprofile.post');
    Route::patch('/myprofile', [\App\Http\Controllers\Front\UserController::class, 'update'])->name('myprofile.update');

});


// Frontend View
Route::get('/', 'App\Http\Controllers\Front\HomepageController@index')->name('homepage');
Route::get('page', 'App\Http\Controllers\Front\HomepageController@index');
Route::get('/category/{category}', 'App\Http\Controllers\Front\HomepageController@category')->name('category');
Route::get('/{category}/{slug}', 'App\Http\Controllers\Front\HomepageController@single')->name('single');
Route::get('/contact', 'App\Http\Controllers\Front\HomepageController@contact')->name('contact');
Route::post('/contact', 'App\Http\Controllers\Front\HomepageController@postcontact')->name('post.contact');
Route::get('/{sayfa}', 'App\Http\Controllers\Front\HomepageController@page')->name('page');


Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

resources/views/back/layouts/footer.blade.php
<div class="row">
    <div class="col-md-12">
        <div class="copyright">
            <p>Copyright © 2018 Colorlib. All rights reserved. Template by <a href="https://colorlib.com">Colorlib</a>.</p>
        </div>
    </div>
</div>
</div>
</div>
</div>
<!-- END MAIN CONTENT-->
<!-- END PAGE CONTAINER-->
</div>

</div>

<!-- Jquery JS-->
<script src="{{asset('back/')}}/vendor/jquery-3.2.1.min.js"></script>
<!-- Bootstrap JS-->
<script src="{{asset('back/')}}/vendor/bootstrap-4.1/popper.min.js"></script>
<script src="{{asset('back/')}}/vendor/bootstrap-4.1/bootstrap.min.js"></script>
<!-- Vendor JS       -->
<script src="{{asset('back/')}}/vendor/slick/slick.min.js">
</script>
<script src="{{asset('back/')}}/vendor/wow/wow.min.js"></script>
<script src="{{asset('back/')}}/vendor/animsition/animsition.min.js"></script>
<script src="{{asset('back/')}}/vendor/bootstrap-progressbar/bootstrap-progressbar.min.js">
</script>
<script src="{{asset('back/')}}/vendor/counter-up/jquery.waypoints.min.js"></script>
<script src="{{asset('back/')}}/vendor/counter-up/jquery.counterup.min.js">
</script>
<script src="{{asset('back/')}}/vendor/circle-progress/circle-progress.min.js"></script>
<script src="{{asset('back/')}}/vendor/perfect-scrollbar/perfect-scrollbar.js"></script>
<script src="{{asset('back/')}}/vendor/chartjs/Chart.bundle.min.js"></script>
<script src="{{asset('back/')}}/vendor/select2/select2.min.js"></script>

<!-- Main JS-->
<script src="{{asset('back/')}}/js/main.js"></script>

@yield('js')
@toastr_js
@toastr_render
</body>
</html>
<!-- end document-->

resources/views/back/layouts/header.blade.php
<!-- PAGE CONTAINER-->
<div class="page-container">
    <!-- HEADER DESKTOP-->
    <header class="header-desktop">
        <div class="section__content section__content--p30">
            <div class="container-fluid">
                <div class="header-wrap">
                    <form class="form-header" action="" method="POST">
                        <input class="au-input au-input--xl" type="text" name="search" placeholder="Search for datas &amp; reports..." />
                        <button class="au-btn--submit" type="submit">
                            <i class="zmdi zmdi-search"></i>
                        </button>
                    </form>
                    <div class="header-button">
                        <div class="noti-wrap">
                            <div class="noti__item js-item-menu">
                                <i class="zmdi zmdi-comment-more"></i>
                                <span class="quantity">1</span>
                                <div class="mess-dropdown js-dropdown">
                                    <div class="mess__title">
                                        <p>You have 2 news message</p>
                                    </div>
                                    <div class="mess__item">
                                        <div class="image img-cir img-40">
                                            <img src="{{asset('back/')}}/images/icon/avatar-06.jpg" alt="Michelle Moreno" />
                                        </div>
                                        <div class="content">
                                            <h6>Michelle Moreno</h6>
                                            <p>Have sent a photo</p>
                                            <span class="time">3 min ago</span>
                                        </div>
                                    </div>
                                    <div class="mess__item">
                                        <div class="image img-cir img-40">
                                            <img src="{{asset('back/')}}/images/icon/avatar-04.jpg" alt="Diane Myers" />
                                        </div>
                                        <div class="content">
                                            <h6>Diane Myers</h6>
                                            <p>You are now connected on message</p>
                                            <span class="time">Yesterday</span>
                                        </div>
                                    </div>
                                    <div class="mess__footer">
                                        <a href="#">View all messages</a>
                                    </div>
                                </div>
                            </div>
                            <div class="noti__item js-item-menu">
                                <i class="zmdi zmdi-email"></i>
                                <span class="quantity">1</span>
                                <div class="email-dropdown js-dropdown">
                                    <div class="email__title">
                                        <p>You have 3 New Emails</p>
                                    </div>
                                    <div class="email__item">
                                        <div class="image img-cir img-40">
                                            <img src="{{asset('back/')}}/images/icon/avatar-06.jpg" alt="Cynthia Harvey" />
                                        </div>
                                        <div class="content">
                                            <p>Meeting about new dashboard...</p>
                                            <span>Cynthia Harvey, 3 min ago</span>
                                        </div>
                                    </div>
                                    <div class="email__item">
                                        <div class="image img-cir img-40">
                                            <img src="{{asset('back/')}}/images/icon/avatar-05.jpg" alt="Cynthia Harvey" />
                                        </div>
                                        <div class="content">
                                            <p>Meeting about new dashboard...</p>
                                            <span>Cynthia Harvey, Yesterday</span>
                                        </div>
                                    </div>
                                    <div class="email__item">
                                        <div class="image img-cir img-40">
                                            <img src="{{asset('back/')}}/images/icon/avatar-04.jpg" alt="Cynthia Harvey" />
                                        </div>
                                        <div class="content">
                                            <p>Meeting about new dashboard...</p>
                                            <span>Cynthia Harvey, April 12,,2018</span>
                                        </div>
                                    </div>
                                    <div class="email__footer">
                                        <a href="#">See all emails</a>
                                    </div>
                                </div>
                            </div>
                            <div class="noti__item js-item-menu">
                                <i class="zmdi zmdi-notifications"></i>
                                <span class="quantity">3</span>
                                <div class="notifi-dropdown js-dropdown">
                                    <div class="notifi__title">
                                        <p>You have 3 Notifications</p>
                                    </div>
                                    <div class="notifi__item">
                                        <div class="bg-c1 img-cir img-40">
                                            <i class="zmdi zmdi-email-open"></i>
                                        </div>
                                        <div class="content">
                                            <p>You got a email notification</p>
                                            <span class="date">April 12, 2018 06:50</span>
                                        </div>
                                    </div>
                                    <div class="notifi__item">
                                        <div class="bg-c2 img-cir img-40">
                                            <i class="zmdi zmdi-account-box"></i>
                                        </div>
                                        <div class="content">
                                            <p>Your account has been blocked</p>
                                            <span class="date">April 12, 2018 06:50</span>
                                        </div>
                                    </div>
                                    <div class="notifi__item">
                                        <div class="bg-c3 img-cir img-40">
                                            <i class="zmdi zmdi-file-text"></i>
                                        </div>
                                        <div class="content">
                                            <p>You got a new file</p>
                                            <span class="date">April 12, 2018 06:50</span>
                                        </div>
                                    </div>
                                    <div class="notifi__footer">
                                        <a href="#">All notifications</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="account-wrap">
                            <div class="account-item clearfix js-item-menu">
                                <div class="image">
                                    <img src="{{asset('back/')}}/images/icon/avatar-01.jpg" />
                                </div>
                                <div class="content">
                                    <a class="js-acc-btn" href="#">{{Auth::user()->name}}</a>
                                </div>
                                <div class="account-dropdown js-dropdown">
                                    <div class="info clearfix">
                                        <div class="image">
                                            <a href="#">
                                                <img src="{{asset('back/')}}/images/icon/avatar-01.jpg" alt="John Doe" />
                                            </a>
                                        </div>
                                        <div class="content">
                                            <h5 class="name">
                                                <a href="#">{{Auth::user()->name}}</a>
                                            </h5>
                                            <span class="email">{{Auth::user()->email}}</span>
                                        </div>
                                    </div>
                                    <div class="account-dropdown__body">
                                        <div class="account-dropdown__item">
                                            <a href="#">
                                                <i class="zmdi zmdi-account"></i>Account</a>
                                        </div>
                                        <div class="account-dropdown__item">
                                            <a href="#">
                                                <i class="zmdi zmdi-settings"></i>Setting</a>
                                        </div>
                                        <div class="account-dropdown__item">
                                            <a href="#">
                                                <i class="zmdi zmdi-money-box"></i>Billing</a>
                                        </div>
                                    </div>
                                    <div class="account-dropdown__footer">
                                        <a href="{{route('admin.auth.logout')}}">
                                            <i class="zmdi zmdi-power"></i>Çıkış</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- HEADER DESKTOP-->

resources/views/back/layouts/master.blade.php
@include('back.layouts.sidebar')
@include('back.layouts.header')
@yield('content')
@include('back.layouts.footer')

resources/views/back/layouts/sidebar.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="au theme template">
    <meta name="author" content="Hau Nguyen">
    <meta name="keywords" content="au theme template">

    <!-- Title Page-->
    <title>Dashboard Sayfası</title>

    <!-- Fontfaces CSS-->
    <link href="{{asset('back/')}}/css/font-face.css" rel="stylesheet" media="all">
    <link href="{{asset('back/')}}/vendor/font-awesome-4.7/css/font-awesome.min.css" rel="stylesheet" media="all">
    <link href="{{asset('back/')}}/vendor/font-awesome-5/css/fontawesome-all.min.css" rel="stylesheet" media="all">
    <link href="{{asset('back/')}}/vendor/mdi-font/css/material-design-iconic-font.min.css" rel="stylesheet" media="all">

    <!-- Bootstrap CSS-->
    <link href="{{asset('back/')}}/vendor/bootstrap-4.1/bootstrap.min.css" rel="stylesheet" media="all">

    <!-- Vendor CSS-->
    <link href="{{asset('back/')}}/vendor/animsition/animsition.min.css" rel="stylesheet" media="all">
    <link href="{{asset('back/')}}/vendor/bootstrap-progressbar/bootstrap-progressbar-3.3.4.min.css" rel="stylesheet" media="all">
    <link href="{{asset('back/')}}/vendor/wow/animate.css" rel="stylesheet" media="all">
    <link href="{{asset('back/')}}/vendor/css-hamburgers/hamburgers.min.css" rel="stylesheet" media="all">
    <link href="{{asset('back/')}}/vendor/slick/slick.css" rel="stylesheet" media="all">
    <link href="{{asset('back/')}}/vendor/select2/select2.min.css" rel="stylesheet" media="all">
    <link href="{{asset('back/')}}/vendor/perfect-scrollbar/perfect-scrollbar.css" rel="stylesheet" media="all">
    <link href="{{asset('back/')}}/css/bootstrap.min.css" rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="{{asset('back/')}}/css/theme.css" rel="stylesheet" media="all">
    @toastr_css
    @yield('css')
</head>

<body class="animsition">
<div class="page-wrapper">
    <!-- HEADER MOBILE-->
    <header class="header-mobile d-block d-lg-none">
        <div class="header-mobile__bar">
            <div class="container-fluid">
                <div class="header-mobile-inner">
                    <a class="logo" href="{{asset('back/')}}/index.html">
                        <img src="{{asset($setting->logo)}}" alt="Umutlion logo" />
                    </a>
                    <button class="hamburger hamburger--slider" type="button">
                            <span class="hamburger-box">
                                <span class="hamburger-inner"></span>
                            </span>
                    </button>
                </div>
            </div>
        </div>

    </header>
    <!-- END HEADER MOBILE-->

    <!-- MENU SIDEBAR-->
    <aside class="menu-sidebar d-none d-lg-block">
        <div class="logo">
            <a href="{{route('admin.dashboard')}}">
                <img src="{{asset($setting->logo)}}" alt="Umutlion Logo" />
            </a>
        </div>
        <div class="menu-sidebar__content js-scrollbar1">
            <nav class="navbar-sidebar">
                <ul class="list-unstyled navbar__list">
                    <li class="has-sub">
                        <a class="js-arrow" href="">
                            <i class="fas fa-tachometer-alt"></i>Post Page</a>
                    </li>
                    <li>
                        <a href="{{route('admin.posts.index')}}">
                            <i class="fas fa-pound-sign"></i>Post Sayfası</a>
                    </li>
                    <li>
                        <a href="{{route('admin.category.index')}}">
                            <i class="fas fa-fw fa-list"></i>Kategoriler</a>
                    </li>
                    <li>
                        <a href="{{route('admin.pages.index')}}">
                            <i class="fas fa-fw fa-folder"></i>Eklenebilir Sayfalar</a>
                    </li>
                    <li>
                        <a href="{{route('admin.users.index')}}">
                            <i class="fas fa-fw fa-user"></i>Kullanıcılar</a>
                    </li>
                    <li>
                        <a href="{{route('admin.settings.index')}}">
                            <i class="fas fa-fw fa-cogs"></i>Ayarlar</a>
                    </li>
                </ul>
            </nav>
        </div>
    </aside>
    <!-- END MENU SIDEBAR-->
</div>