routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Front\UserController;
use Illuminate\Foundation\Application;

use Inertia\Inertia;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
#Route::get('admin/panel','App\Http\Controllers\Back\Dashboard@index')->name('admin.dashboard');

Route::get('/', function () {
    return Inertia::render('Welcome', [
        'canLogin' => Route::has('login'),
        'canRegister' => Route::has('register'),
        'laravelVersion' => Application::VERSION,
        'phpVersion' => PHP_VERSION,
    ]);
});


// Admin

Route::get('admin/login', 'App\Http\Controllers\Admin\HomeController@login')->name('admin.auth.login');
Route::post('admin/login', 'App\Http\Controllers\Admin\HomeController@login_post')->name('admin.auth.login.post');


Route::prefix('admin')->name('admin.')->middleware('Admin')->group(function () {
    //user roles

    // posts
    Route::get('/', 'App\Http\Controllers\Admin\HomeController@index')->name('dashboard');
    Route::resource('posts', 'App\Http\Controllers\Admin\PostsController');
    Route::get('logout', 'App\Http\Controllers\Admin\HomeController@logout')->name('auth.logout');
    Route::get('register', 'App\Http\Controllers\Admin\HomeController@register')->name('auth.register');
    Route::get('forgetpassword', 'App\Http\Controllers\Admin\HomeController@forget')->name('auth.forget');
    Route::get('posts', 'App\Http\Controllers\Admin\PostsController@index')->name('posts.index');
    Route::get('switch', 'App\Http\Controllers\Admin\PostsController@switch')->name('switch');
    Route::put('hot_posts', 'App\Http\Controllers\Admin\PostsController@hot_posts')->name('hot_posts');
    Route::get('posts/create', 'App\Http\Controllers\Admin\PostsController@create')->name('posts.create');
    Route::get('create/{post_id}', 'App\Http\Controllers\Admin\ImageController@create')->name('admin_image_add');
    Route::post('store/{post_id}', 'App\Http\Controllers\Admin\ImageController@store')->name('admin_image_store');
    Route::get('delete/{id}/{post_id}', 'App\Http\Controllers\Admin\ImageController@destroy')->name('admin_image_delete');
    Route::get('show', 'App\Http\Controllers\Admin\ImageController@show')->name('admin_image_show');
    // Category
    Route::get('/categories', 'App\Http\Controllers\Admin\CategoryController@index')->name('category.index');
    Route::post('/categories/create', 'App\Http\Controllers\Admin\CategoryController@create')->name('category.create');
    Route::post('/categories/update', 'App\Http\Controllers\Admin\CategoryController@update')->name('category.update');
    Route::post('/categories/delete', 'App\Http\Controllers\Admin\CategoryController@delete')->name('category.delete');
    Route::post('/posts/delete/{id}', 'App\Http\Controllers\Admin\PostsController@delete')->name('posts.delete');
    Route::get('/categories/getData', 'App\Http\Controllers\Admin\CategoryController@getData')->name('category.getdata');
    // Page Route
    Route::get('/pages', 'App\Http\Controllers\Admin\PageController@index')->name('pages.index');
    Route::get('/pages/create', 'App\Http\Controllers\Admin\PageController@create')->name('pages.create');
    Route::post('/pages/create', 'App\Http\Controllers\Admin\PageController@createpost')->name('pages.create.post');
    Route::get('/pages/update/{id}', 'App\Http\Controllers\Admin\PageController@update')->name('pages.update');
    Route::post('/pages/update/{id}', 'App\Http\Controllers\Admin\PageController@updatepost')->name('pages.update.post');
    Route::get('/pages/switch', 'App\Http\Controllers\Admin\PageController@switch')->name('pages.switch');
    Route::post('/pages/delete/{id}', 'App\Http\Controllers\Admin\PageController@delete')->name('pages.delete');
    // Settings
    Route::get('/settings', 'App\Http\Controllers\Admin\SettingsController@index')->name('settings.index');
    Route::post('settings/update', 'App\Http\Controllers\Admin\SettingsController@update')->name('settings.update');

    // roles

    Route::get('/users', 'App\Http\Controllers\Admin\UserController@index')->name('users.index');
    Route::get('/users/create', 'App\Http\Controllers\Admin\UserController@create')->name('users.create');

    Route::post('/users/create', 'App\Http\Controllers\Admin\UserController@store')->name('users.store');
    Route::get('/users/{user}/edit', 'App\Http\Controllers\Admin\UserController@edit')->name('users.edit');
    Route::put('/users/{user}/update', 'App\Http\Controllers\Admin\UserController@update')->name('users.update');
    Route::delete('/users/{user}/delete', 'App\Http\Controllers\Admin\UserController@destroy')->name('users.destroy');

});


// User Login Route
Route::post('/user-login', [\App\Http\Controllers\Front\UserController::class, 'myprofile_post'])->name('user.login');
// User View
Route::middleware('auth')->prefix('myuser')->name('myuser.')->group(function () {
    Route::get('/myprofile', [\App\Http\Controllers\Front\UserController::class, 'index'])->name('myprofile');
    Route::post('/', [\App\Http\Controllers\Front\UserController::class, 'login_post'])->name('myprofile.post');
    Route::patch('/myprofile', [\App\Http\Controllers\Front\UserController::class, 'update'])->name('myprofile.update');

});


// Frontend View
Route::get('/', 'App\Http\Controllers\Front\HomepageController@index')->name('homepage');
Route::get('page', 'App\Http\Controllers\Front\HomepageController@index');
Route::get('/category/{category}', 'App\Http\Controllers\Front\HomepageController@category')->name('category');
Route::get('/{category}/{slug}', 'App\Http\Controllers\Front\HomepageController@single')->name('single');
Route::get('/contact', 'App\Http\Controllers\Front\HomepageController@contact')->name('contact');
Route::post('/contact', 'App\Http\Controllers\Front\HomepageController@postcontact')->name('post.contact');
Route::get('/{sayfa}', 'App\Http\Controllers\Front\HomepageController@page')->name('page');


Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Fortify\TwoFactorAuthenticatable;
use Laravel\Jetstream\HasProfilePhoto;
use Laravel\Sanctum\HasApiTokens;
use Illuminate\Support\Collection;

class User extends Authenticatable
{
    use HasApiTokens;
    use HasFactory;
    use HasProfilePhoto;
    use Notifiable;
    use TwoFactorAuthenticatable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
        'two_factor_recovery_codes',
        'two_factor_secret',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function setPasswordAttribute($value){
        $this->attributes['password']=bcrypt($value);
    }

    /**
     * The accessors to append to the model's array form.
     *
     * @var array
     */
    protected $appends = [
        'profile_photo_url',
    ];

    public function roles(){
        return $this->belongsToMany(Role::class);
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Http\Request;
use Spatie\Permission\Models\Role;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */


    public function index()
    {
        $users = User::all();
        return view('back.users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('back.users.create')->with('roles', $this->roles);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $user = User::create([
            'name'=>$request->name,
            'email'=>$request->email,
            'password'=>bcrypt($request->password),
        ]);

        return redirect()->route('back.users.index')->with('success', $user->name. "User created cusses");
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return view('back.users.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $user->update($request->all());
        return redirect()->route('admin.users.index')->with('success', $user->name. "updated başarılı");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->delete();
        return redirect()->route('admin.users.index')->with('success', $user->name. "destroy başarılı");
    }

}

app/Http/Controllers/Front/UserController.php
<?php

namespace App\Http\Controllers\Front;

use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Models\Page;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

use App\Models\Admin;
use Illuminate\Support\Str;


class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function __construct()
    {
        view()->share('pages', Page::orderBy('order', 'ASC')->get());
        view()->share('categories', Category::inRandomOrder()->get());
        //$this->middleware('Admin');
    }

    public function index()
    {
        return view('front.user_profile');
    }

    public function login()
    {
        return view('dashboard');
    }

    public function myprofile_post(Request $request)
    {
        if (Auth::guard('users')->attempt(['email' => $request->email, 'password' => $request->password])) {
            toastr()->success('Selam!', 'Tekrardan hoşgeldin. Welcome back!');
            return redirect()->route('homepage');
        }
        return redirect()->route('homepage')->withErrors('Email veya parola hatalı.');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param \App\Models\User $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Models\User $user
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function edit()
    {
        return view('front.user_profile')->with('user', \auth()->user());

    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\User $user
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request)
    {
        dd($request->all());
    }
    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\User $user
     * @return \Illuminate\Http\RedirectResponse
     */

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Models\User $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        //
    }


}

resources/views/back/users/create.blade.php
@extends('back.layouts.master')
@section('title', 'Users PAGE')
@section('content')
    <br>
    <br>
    <div class="d-flex justify-content-between">
        <a href="{{route('admin.users.create')}}" class="btn btn-primary rounded">Create user</a>
    </div>
    <h3 class="text-center">Create a new user</h3>
    <form action="{{route('admin.users.store')}}" method="POST">
        @csrf
        <div class="form-group">
            <label for="name">Name</label>
            <input id="name"
                   type="text"
                   class="form-control"
                   name="name"
                   placeholder="Enter user name">
        </div>
        <div class="form-group">
            <label for="email">Email</label>
            <input id="email"
                   type="text"
                   class="form-control"
                   name="email"
                   placeholder="Enter user email">
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input id="password"
                   type="text"
                   class="form-control"
                   name="password"
                   placeholder="Enter user password">
        </div>
        <button class="btn btn-success btn-block rounded">Save User</button>
    </form>

@endsection

resources/views/back/users/edit.blade.php
@extends('back.layouts.master')
@section('title', 'Edit PAGE')
@section('content')
    <br>
    <br>
    <div class="d-flex justify-content-between">
        <a href="{{route('admin.users.create')}}" class="btn btn-primary rounded">Create user</a>
    </div>
    <h3 class="text-center">Update {{$user->name}}</h3>
    <form action="{{route('admin.users.update', [$user->id])}}" method="POST">
        @csrf
        @method('PUT')
        <div class="form-group">
            <label for="name">Name</label>
            <input id="name"
                   type="text"
                   class="form-control"
                   name="name"
                   placeholder="Enter user name"
                   value="{{$user->name}}" >
        </div>
        <div class="form-group">
            <label for="email">Email</label>
            <input id="email"
                   type="text"
                   class="form-control"
                   name="email"
                   placeholder="Enter user email"
                   value="{{$user->email}}">
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input id="password"
                   type="text"
                   class="form-control"
                   name="password"
                   placeholder="Enter user password"
                   value="{{$user->password}}">
        </div>
        <button class="btn btn-success btn-block rounded">Save User</button>
    </form>

@endsection

resources/views/back/users/index.blade.php
@extends('back.layouts.master')
@section('title', 'Users PAGE')
@section('content')
    <br>
    <br>
    <div class="d-flex justify-content-between">
        <a href="{{route('admin.users.create')}}" class="btn btn-primary rounded">Create user</a>
    </div>
    <h2>All Users</h2>
    @if(session('success'))
        <div class="aler alert-success">
            {{session('success')}}
        </div>
    @endif
    <table class="table table-hover">
        <tr>
            <th>User Name</th>
            <th>User Email</th>
            <th>User Role</th>
        </tr>
        @foreach($users as $user)
        <tr>
            <td>{{$user->name}}</td>
            <td>{{$user->email}}</td>
            <td>
                Admin

            </td>
            <td>
                <a href="{{route('admin.users.edit', [$user->id])}}" class="btn btn-warning btn-sm rounded">
                    <i class="meterial-icons">edit</i>
                    Edit
                </a>
                <form action="{{route('admin.users.destroy', [$user->id])}}" method="post">
                    @csrf
                    @method('DELETE')
                    <button type="submit" class="btn-danger btn-sm rounded">
                        <i class="meterial-icons">edit</i>
                        Delete
                    </button>
                </form>
            </td>
        </tr>
        @endforeach
    </table>
@endsection